service: aws-node-project

frameworkVersion: '3'

plugins:
  - serverless-rollup-plugin

custom:
  rollup:
    config: ./rollup.config.js

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
